### ISSUE TITLE
F-Droid FOSS repository needs update to 1.6 version w/URL fix

### ISSUE THREAD

**Issue by sysfu** [voidcode/Diaspora-Webclient#12]
Android market version has been updated but the one in the F-Droid FOSS repository is still v1.5 with the broken URL. Please update when possible.

**Comment by voidcode** [comment]
It should be updated to version 1.6.1 now

**Comment by sysfu** [comment]
Latest version displayed in F-Droid repo app is still v1.5. This is after updating the application list. Any suggested troubleshooting steps?

**Comment by sysfu** [comment]
You can see that the F-Droid web site still displays v1.5 as the latest available version too. http://f-droid.org/repository/browse/?fdid=com.voidcode.diasporawebclient&fdpage=2

**Comment by voidcode** [comment]
I do not know F-droid and therefore I do not quite how they download the apk-file to the site. 
But perhaps the problem is that it gets the wrong apk file from the bin folder on github(there are two in the bin folder).
The right apk-file(v1.6.2) is https://github.com/voidcode/Diaspora-Webclient/blob/master/bin/Diaspora-Webclient.apk

**Comment by sysfu** [comment]
Ah OK, I had assumed that you had submitted the application to F-Droid and were responsible for updating it. 

So what you're telling me is that someone who administers the F-Droid repository decided of their own volition to include your application, and that you were not, and are not involved?

**Comment by CiaranG** [comment]
All applications in F-Droid are built from source, so there is no apk download involved. However, recent versions of Diaspora-Webclient don't build - the source appears to be either incomplete or incorrect. Example:

 build/com.voidcode.diasporawebclient/res/layout/settings.xml:25: error: Error: No resource found that matches the given name (at 'text' with value '@string/settings_currentpod').

Although the file is referring to that string value, it doesn't exist in the source. There are several other similar instances.

**Comment by voidcode** [comment]
Nop I am not the admin of the F-Droid repository, but I am pleased that some want to do this :)
Ok I have delete @string/settings_currentpod from the string.xml and commit it to github.
It was just some old data from a different version of the app.
I need a log of the other instances before I can fix them.

@CiaranG 
Does it mean F-Droid can not built an app just because res/values/string.xml has a empty string? 
https://github.com/voidcode/Diaspora-Webclient/commit/2dbbeac8b6bb147ee3d9c9abea5b00b11fd20dc0

**Comment by CiaranG** [comment]
Not exactly - it can't build an app if it doesn't compile. I'm not even sure how you're compiling it, unless your source is different to what's here. Here are another two:

 build/com.voidcode.diasporawebclient/res/layout/settings.xml:18: error: Error: No resource found that matches the given name (at 'text' with value '@string/settings_text_currentpod')
 build/com.voidcode.diasporawebclient/res/layout/settings.xml:38: error: Error: No resource found that matches the given name (at 'text' with value '@string/settings_button_save').

Both those lines in settings.xml refer to strings that don't exist (nothing to do with anything being blank - they just aren't defined at all, anywhere in the code)

**Comment by sysfu** [comment]
Any progress on getting the app to build properly?

**Comment by voidcode** [comment]
Yes.
Try to see if it works now...
I have run a git commit -a.
So now I get no error when I run: git clone git@github.com:voidcode/Diaspora-Webclient.git
